# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161019_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Image'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
